feat: add functionality of internal pysat solvers running
avsmal/circuitsat pull request #11
Opened 2021-11-14 14:19 UTC by 1DarkLord1

Добавил поддержку запуска на внутренних солверах"из коробки", замера времени отдельно трансформации CNF и решения SAT

2021-11-14 18:23 UTC, spefk requested changes
Не успеваю подробно вчитаться, но
Из главного:
1. Есть ощущение, что можно порефкаторить `csat_instances_runner` и сделать его более гранулярным, от чего он должен бы подсократиться (т.к. там достаточно много повторов, а суть примерно одна);
2. Надо порефакторить `statistics_printer`. Его точно можно сделать более гранулярным;
3. Надо поправить замечания mypy (у меня он ругается);
4. Просто взять и запустить cli у меня не вышло, нужно небольшую инструкцию в readme репозитория допилить.

2021-11-14 18:23 UTC, spefk commented on instances_runner/entities/statistics_printer.py
> +        logger.info(f'Runs failed by time limit: {num_tl}/{self._common_stat.size}')
Повторяющийя кусок кода. Возможно, стоит вынести во внутренний метод класса, idk

2021-11-14 18:23 UTC, spefk commented on instances_runner/entities/statistics_printer.py
> +        logger.info(f'Runs failed by time limit: {num_tl}/{self._common_stat.size}')
Если правильно понял, то:
лучше чтоб `ExtendedStatisticsPrinter` наследовался от `CommonStatisticsPrinter`, и буквально расширял его. Тогда и кода было бы сильно меньше. Сами методы `display_statistics` и `save_plot` при этом можно разбить на вызов некоторых внутренних методов, и, в зависимости от класса, переопределять уже какие именно из них вызываются.

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/exceptions/exceptions.py
> +        super().__init__()
Сделал

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/entities/csat_instances_runner.py
> +from exceptions.exceptions import *
Сделал

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/entities/statistics_collector.py
> +from exceptions.exceptions import *
Сделал

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/entities/statistics_collector.py
> +    """
Сделал

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/entities/statistics_printer.py
> +from exceptions.exceptions import *
Сделал

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/entities/csat_instances_runner.py
> +import abc
Поменял

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/entities/csat_instances_runner.py
> +    """
Сделал

2021-11-22 20:57 UTC, 1DarkLord1 commented on instances_runner/entities/csat_instances_runner.py
> +                solver is None):
Убрал перенос

2021-11-22 20:58 UTC, 1DarkLord1 commented on instances_runner/entities/csat_instances_runner.py
> +        """
Исправил

2021-11-22 20:58 UTC, 1DarkLord1 commented on instances_runner/entities/csat_instances_runner.py
> +        )
Занес

2021-11-22 20:58 UTC, 1DarkLord1 commented on instances_runner/entities/statistics_printer.py
> +        logger.info(f'Runs failed by time limit: {num_tl}/{self._common_stat.size}')
Сделал

2021-11-28 16:07 UTC, spefk commented on instances_runner/exceptions/exceptions.py
> +        super().__init__()
В них можно не переопределять __init__, но ладно, вроде не страшно

2021-11-28 16:22 UTC, spefk commented
По графику не понятно, какой имено инстанс обозначен на оси (просто номера), надо подписывать именами либо давать расшифровку. При этом файлы директория читаются в странном порядке:
```bash
_plot.png --time_limit 3 --runs_count 20
Instance running |████████████████████████████████| 6/6
2021-11-28 19:16:17 [    INFO] statistics_printer: Runs failed by runtime error: 0/6 (statistics_printer.py:  81)
2021-11-28 19:16:17 [    INFO] statistics_printer: Runs failed by time limit: 0/6 (statistics_printer.py:  82)
2021-11-28 19:16:17 [    INFO] statistics_printer: 
Common statistics:
mean: 0.070s
std: 0.147s
median: 0.000s
min: 0.000s
max: 0.399s (statistics_printer.py:  67)
2021-11-28 19:16:17 [    INFO] statistics_printer: 
Full execution info:
test2.bench: 0.000s
test6_unsat.bench: 0.000s
test5.bench: 0.399s
test3.bench: 0.000s
test1.bench: 0.000s
test4.bench: 0.019s (statistics_printer.py:  51)
```

Почему-то `Runs failed by runtime error: 0/6`, хотя я указал 20 запусков

2021-11-28 16:33 UTC, 1DarkLord1 commented
> По графику не понятно, какой имено инстанс обозначен на оси (просто номера), надо подписывать именами либо давать расшифровку. При этом файлы директория читаются в странном порядке:
> 
> ```shell
> _plot.png --time_limit 3 --runs_count 20
> Instance running |████████████████████████████████| 6/6
> 2021-11-28 19:16:17 [    INFO] statistics_printer: Runs failed by runtime error: 0/6 (statistics_printer.py:  81)
> 2021-11-28 19:16:17 [    INFO] statistics_printer: Runs failed by time limit: 0/6 (statistics_printer.py:  82)
> 2021-11-28 19:16:17 [    INFO] statistics_printer: 
> Common statistics:
> mean: 0.070s
> std: 0.147s
> median: 0.000s
> min: 0.000s
> max: 0.399s (statistics_printer.py:  67)
> 2021-11-28 19:16:17 [    INFO] statistics_printer: 
> Full execution info:
> test2.bench: 0.000s
> test6_unsat.bench: 0.000s
> test5.bench: 0.399s
> test3.bench: 0.000s
> test1.bench: 0.000s
> test4.bench: 0.019s (statistics_printer.py:  51)
> ```
> 
> Почему-то `Runs failed by runtime error: 0/6`, хотя я указал 20 запусков

А почему должны быть runtime error? Как количество запусков кореллирует с этим?

2021-11-28 16:44 UTC, spefk commented
Количество запусков это количество повторов расчетов на одном экземпляре ведь? Каждый из них может кинуть исключение ведь? Или нет?

2021-11-28 16:48 UTC, spefk requested changes
Структурно глянул, вроде все +- Oк

Но надо пару мелочей поправить

Еще можно попросить @egdegd поревьюить сбор статистики 😃

2021-11-28 16:48 UTC, spefk commented on instances_runner/cli
> +    csat_instances_runner_cli()
Лучше чтобы в cli был только запуск cli, а остальное импортировалось из модулей рядом (в соседней директории)

2021-11-28 16:48 UTC, spefk commented on instances_runner/cli
> +)
Имена флагов и опций в CLI принято через `-` а не через `_` делать. При этом `-` автоматически превращается CLICK'ом в `_` в имени переменных

2021-11-28 16:48 UTC, spefk commented on instances_runner/cli
> +        else ProgramType.internal_solver,
Такие условия лучше выделять скобками, или даже в отдельные переменные
```py
    runner = CSATInstancesRunnerInternal(
        (
            ProgramType.csat_to_cnf_transformator
            if only_translation
            else ProgramType.internal_solver
        ),
        input_dir,
        plot_path,
        time_limit,
        runs_count,
        solver,
    )
```

2021-11-28 16:48 UTC, spefk commented on instances_runner/cli
> +    """
В коде примеры лучше выглядят вот так, например:
```py
    """
    Runs internal solver on CircuitSAT instances and calculate some statistics
    
    Examples:
        >> python cli internal-solver-runner
            --solver cadical
            --input_dir /home/dir/bench
            --plot_path /home/dir/results/plot.png
            --time_limit 0.5
            --runs_count 3

        >> python cli internal-solver-runner
            --only_translation
            --input_dir /home/dir/bench
            --plot_path /home/dir/results/plot.png
            --time_limit 0.5
            --runs_count 3
    
    """
```

Про то, что выдает help CLICK -- можно пробовать задавать отдельное форматирование

Минорно

2021-11-28 16:48 UTC, spefk commented on instances_runner/entities/statistics_printer.py
> +        display_stat_records('SAT solving statistics:', self._solve_pysat_stat.stat)
лучше добавить эти строки именно в `_display_only_common_statistics`, вызвав там `super`, а `display_statistics` не трогать

2021-11-28 16:48 UTC, spefk commented on instances_runner/entities/statistics_printer.py
> +        display_stat_records('SAT solving statistics:', self._solve_pysat_stat.stat)
Вообще, можно чтобы в базовом классе был определен `display_statistics`, которые вызывает фиксированные методы (абстрактные). А в детях уже только их переопределять, например

2021-11-28 16:48 UTC, spefk commented on instances_runner/entities/csat_instances_runner.py
> +                )
PyCharm вот тут на типы орет. MyPy запускал?

2021-11-28 16:50 UTC, 1DarkLord1 commented on instances_runner/entities/csat_instances_runner.py
> +                )
Запускал, все норм

2021-11-28 16:52 UTC, 1DarkLord1 commented
> Количество запусков это количество повторов расчетов на одном экземпляре ведь? Каждый из них может кинуть исключение ведь? Или нет?

А ты подал на вход инстансы, на которых солвер должен кидать какие-то исключения?

2021-11-28 16:55 UTC, spefk commented
Я о том, что знаменатель 6, а не 6 * 20, по количеству запусков солвера

2021-11-28 16:56 UTC, 1DarkLord1 commented
> Я о том, что знаменатель 6, а не 6 * 20, по количеству запусков солвера

6, потому что всего 6 инстансов, каждый прогоняется 20 раз

2021-11-28 17:07 UTC, spefk commented
Но на каждом из 20 запусков ведь может быть runtime_error? или как?

2021-11-28 17:08 UTC, spefk commented
В целом, надо чтобы кто-то глянул сбор статистики, пофиксить мелочи, о которых я написал, и, думаю, можно будет мержить

2021-11-28 17:22 UTC, 1DarkLord1 commented
> Но на каждом из 20 запусков ведь может быть runtime_error? или как?

Да, может быть

2021-12-05 15:28 UTC, 1DarkLord1 commented on instances_runner/entities/statistics_printer.py
> +        display_stat_records('SAT solving statistics:', self._solve_pysat_stat.stat)
Я в итоге сделал так, чтобы display_statistics выводил только общую статистику (min, max, std, mean), а чтобы вывести результаты на каждом инстансе, надо дернуть display_full_execution_info

2021-12-05 15:28 UTC, 1DarkLord1 commented on instances_runner/cli
> +    """
Сделал

2021-12-05 15:28 UTC, 1DarkLord1 commented on instances_runner/cli
> +        else ProgramType.internal_solver,
Исправил

2021-12-05 15:28 UTC, 1DarkLord1 commented on instances_runner/cli
> +)
Исправил

2021-12-05 15:28 UTC, 1DarkLord1 commented on instances_runner/cli
> +    csat_instances_runner_cli()
Исправил

2021-12-07 12:40 UTC, spefk commented on instances_runner/cli
> +    csat_instances_runner_cli()
Разбить содержимое текущего cli на разные файлы, а в самом файле cli только запускаться. Вроде, это не должно быть сложно сделать, но будет читаемее. Те получится, например, отдельная директория `/cli`, в которой будут файлы вроде `/cli/internal_solver_runner.py`, `/cli/external_solver_runner.py`.

Сам PR постараюсь завтра глянуть.

2021-12-18 16:44 UTC, merged