Hard instances generation
avsmal/circuitsat pull request #8
Opened 2021-10-30 11:20 UTC by egdegd

2021-11-14 23:24 UTC, spefk requested changes
Пробежался по началу, дальше пока-что не вчитывался

Много где происходит "ручное" добавление гейтов, инкрементирование счетчика "последнего гейта" и, иногда, использование "сайд эффектов" (например, после работы `at_most_k`, использование последнего добавленного гейта для конструирования общего AND  в `ECP`).

ИМХО, очень просто тут ошибиться, и сложно такое валидировать глазами. С ходу, из возможных вариантов решения вижу:
1. Покрыть тестами (см. pytest) генерацию мелких случаев для каждого типа экземпляра задачи;
2. Сделать интерфейс для добавления гейтов в Circuit, который сам следил бы за инкрементацией и прочим.

Возможно, не стоит этого делать, предлагаю дискутировать

2021-11-14 23:24 UTC, spefk commented on circuit_generator/encoding_of_hard_principles.py
> +        and_gate_numbers.append(cur_gate)
Очень непрозрачно что последний из добавленных `at_most_2_from_4` (или `at_most_k`) гейтов нужно добавлять в and
Что делнть -- не понятно. Можно комментарий оставить

2021-11-14 23:24 UTC, spefk commented on .gitignore
> +>>>>>>> c2e6a48adb5248eaf9a0f09b0b1d47919717f172
видимо во время merge conflict осталось

2021-11-14 23:24 UTC, spefk commented on circuit_generator/encoding_of_hard_principles.py
> +    cur_gate += 1
Очень пугает ручная инкрементация кол-ва гейтов, и ручное добавление гейтов в списки -- легко ошибиться.
Может как-нибудь абстрагироваться, и сделать интерфейс добавления гейтов в Circuit, который сам бы следил за инкрементацией и прочим?

Возможно, минорная задача

2021-11-21 13:38 UTC, egdegd commented on circuit_generator/encoding_of_hard_principles.py
> +            cur_gate, new_nodes = at_most_k(deg // 2, cur_gate, edges)
Чтобы получился int, а не float

2021-11-21 13:42 UTC, egdegd commented on circuit_generator/circuit.py
> +        self.output_nodes = output_nodes
Я бы не хотел ограничивать типы строчками, имя гейта может быть как '1', так и 1. Иначе придется все время об этом думать и все оборачивать в str().

2021-11-21 13:44 UTC, egdegd commented on circuit_generator/circuit.py
> +        return len(self.input_nodes), len(self.internal_nodes)
Это самое интересное, что можно возвращать) Добавил комментарий

2021-11-21 13:46 UTC, egdegd commented on circuit_generator/circuit.py
> +            f.write('{g} = {op}({gates})\n'.format(g=lst[1], op=lst[0], gates=', '.join(map(str, lst[2:]))))
Сделал отдельный класс для InternalNode. Но не стал использовать dataclass, так как там получился чуть более сложный, чем тривиальный конструктор

2021-11-28 16:58 UTC, spefk commented on circuit_generator/circuit.py
> +            f.write('{g} = {op}({gates})\n'.format(g=lst[1], op=lst[0], gates=', '.join(map(str, lst[2:]))))
в аргументах `dataclass` можно выключать генерацию того, что не нужно, или явно переопределять

но если другие его возможности не понадобились, то ок 😃

2021-11-28 16:59 UTC, spefk commented on circuit_generator/circuit.py
> +        self.output_nodes = output_nodes
Можно делать `Union` из `typing` и указывать много типов, но это минорно

давай сначала смержим, потом будем разбираться с типами

2021-11-28 17:00 UTC, spefk commented on circuit_generator/circuit.py
> +        return len(self.input_nodes), len(self.internal_nodes)
Хорошо

2021-11-28 17:00 UTC, spefk commented on circuit_generator/encoding_of_hard_principles.py
> +            cur_gate, new_nodes = at_most_k(deg // 2, cur_gate, edges)
Понял

2021-11-28 17:20 UTC, spefk approved these changes
Посмотрел верхнеуровнево -- вроде, в целом ок

Думаю, надо мержить, и потом уже дорабатывать/исправлять, если будет потребность

2021-11-28 17:20 UTC, spefk commented on circuit_generator/circuit.py
> +        self.and_gate_names = []
тут все таки надо типы 😃 

```py
List[InternalNode]
int
```

2021-11-28 17:20 UTC, spefk commented on circuit_generator/encoding_of_hard_principles.py
> +from circuit_generator.encoding_of_operations import *
Наверное, можно писать `.circuit_generator`, если они рядом лежат, чтобы не было доп. проблем с питоновским PATH, и будет нормально

Про то как в целом лучше импорты делать -- подумаю

2021-11-28 17:20 UTC, spefk commented on circuit_generator/graph_generator.py
> +import networkx as nx
надо `networkx` добавить в Pipfile

2021-11-29 17:38 UTC, merged